S004 t39 paging filtering orders
AI-2020-2021-LAB1/stock-exchange-app-backend pull request #14
Opened 2020-11-04 12:56 UTC by pkr5

2020-11-04 13:00 UTC, Karol172 requested changes

2020-11-04 13:00 UTC, karolcymerys commented on src/main/java/com/project/stockexchangeappbackend/repository/OrderRepository.java
> +    Page<Order> findAll(@Nullable Specification specification, Pageable pageable);
Isn't is useless now?

2020-11-04 13:00 UTC, karolcymerys commented on src/main/java/com/project/stockexchangeappbackend/repository/specification/OrderSpecification.java
> +public interface OrderSpecification extends Specification<Order> {
Isn't is useless now?

2020-11-04 13:00 UTC, karolcymerys commented on src/main/java/com/project/stockexchangeappbackend/rest/OrderController.java
> +    //@PreAuthorize("hasAnyRole('ADMIN','USER')")
?

2020-11-04 13:16 UTC, pkr5 commented on src/main/java/com/project/stockexchangeappbackend/rest/OrderController.java
> +    //@PreAuthorize("hasAnyRole('ADMIN','USER')")
my bad

2020-11-05 17:02 UTC, Karol172 approved these changes

2020-11-05 17:02 UTC, Karol172 commented on src/main/java/com/project/stockexchangeappbackend/service/OrderServiceImpl.java
> +        //return allOrdersRepository.findAll(specification, pageable);
remove comment and refactor it

2020-11-06 09:31 UTC, merged