S005-T49
AI-2020-2021-LAB1/stock-exchange-app-backend pull request #37
Opened 2020-11-16 09:56 UTC by pabloducato

2020-11-16 10:30 UTC, Karol172 requested changes

2020-11-16 10:30 UTC, Karol172 commented on src/main/java/com/project/stockexchangeappbackend/rest/UsersController.java
> +    @PreAuthorize("hasRole('USER')")
Admin również powinien mieć tą możliwość

2020-11-16 10:30 UTC, Karol172 commented on src/main/java/com/project/stockexchangeappbackend/rest/UsersController.java
> +    public UserDTO changeDetails(@RequestParam String firstName, @RequestParam String lastName, Principal principal) {
Co jeśli firstName/lastName = null lub " ". Stwórz nowy obiekt DTO lub użyj istniejącego jeśli to możliwe.

2020-11-16 10:30 UTC, Karol172 commented on src/main/java/com/project/stockexchangeappbackend/rest/UsersController.java
> +        return mapper.map(userService.changeUserDetails(user.getId(), firstName, lastName), UserDTO.class);
Podobna sytuacja, jak w przypadku zmiany hasła

2020-11-16 10:30 UTC, Karol172 commented on src/main/java/com/project/stockexchangeappbackend/service/UserServiceImpl.java
> +        user.setFirstName(firstName);
trim()

2020-11-16 10:30 UTC, Karol172 commented on src/main/java/com/project/stockexchangeappbackend/service/UserServiceImpl.java
> +        user.setLastName(lastName);
trim()

2020-11-20 16:16 UTC, pabloducato commented on src/main/java/com/project/stockexchangeappbackend/service/UserServiceImpl.java
> +        user.setLastName(lastName);
Done.

2020-11-20 16:16 UTC, pabloducato commented on src/main/java/com/project/stockexchangeappbackend/service/UserServiceImpl.java
> +        user.setFirstName(firstName);
Done.

2020-11-24 09:10 UTC, Karol172 approved these changes

2020-11-24 09:10 UTC, merged